In [37]:
import duckdb

con = duckdb.connect("../dev.duckdb")
con.execute("""
        SELECT
            year,
            week_of_year,
            cargo_category,
            MIN(full_date) AS start_of_week,
            SUM(number_of_trucks) AS sum_of_trucks,
            SUM(CASE
                WHEN full_date BETWEEN '2023-11-24' AND '2023-12-01' THEN 1
                WHEN full_date BETWEEN '2025-01-19' AND '2025-03-17' THEN 1
                WHEN full_date >= '2025-10-03' THEN 1
                ELSE 0
            END) >= 4 AS is_ceasefire
        FROM main_mart.aid_events
        GROUP BY year, week_of_year, cargo_category
        ORDER BY year, week_of_year, cargo_category
""").df()

,year,week_of_year,cargo_category,start_of_week,sum_of_trucks,is_ceasefire
0,2023,42,Food Items,2023-10-21,16.0,False
1,2023,42,Medical Supplies,2023-10-21,14.0,False
2,2023,42,Mixed Items,2023-10-22,5.0,False
3,2023,43,Food Items,2023-10-23,57.0,False
4,2023,43,Medical Supplies,2023-10-23,30.0,False
...,...,...,...,...,...,...
251,2025,2,Mixed Items,2025-01-09,5.0,False
252,2025,2,Non-Food Items,2025-01-08,24.0,False
253,2025,3,Food Items,2025-01-13,55.0,False
254,2025,3,Mixed Items,2025-01-13,1.0,False
255,2025,3,Non-Food Items,2025-01-13,23.0,False

In [57]:
con = duckdb.connect("../dev.duckdb")
con.execute("""
SELECT commodity_name, unit_amount, price_date, avg_price_before_oct7, COUNT(*)
FROM main_stg.stg_commodity_prices
WHERE avg_price_before_oct7 IS NOT NULL
GROUP BY commodity_name, unit_amount, price_date, avg_price_before_oct7
HAVING COUNT(*) > 1
""").df()

Empty DataFrame
Columns: [commodity_name, unit_amount, price_date, avg_price_before_oct7, count_star()]
Index: []

In [39]:
con.execute(
"""
SELECT
    table_name,
    column_name,
    data_type
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE table_name LIKE 'fct%'
""").df()

              table_name       column_name  data_type
0       fct_aid_received      aid_event_id     BIGINT
1       fct_aid_received           date_id    INTEGER
2       fct_aid_received  number_of_trucks     BIGINT
3       fct_aid_received          cargo_id    VARCHAR
4       fct_aid_received          quantity     BIGINT
5       fct_aid_received             units    VARCHAR
6       fct_aid_received       crossing_id    VARCHAR
7       fct_aid_received       data_period    VARCHAR
8       fct_aid_received       last_edited  TIMESTAMP
9   fct_commodity_prices      commodity_id    VARCHAR
10  fct_commodity_prices           date_id    INTEGER
11  fct_commodity_prices             price     DOUBLE

In [58]:
con.close()