In [9]:
import duckdb

con = duckdb.connect("../dev.duckdb")
con.execute("""
        SELECT
            year,
            week_of_year,
            cargo_category,
            MIN(full_date) AS start_of_week,
            SUM(number_of_trucks) AS sum_of_trucks,
            SUM(CASE
                WHEN full_date BETWEEN '2023-11-24' AND '2023-12-01' THEN 1
                WHEN full_date BETWEEN '2025-01-19' AND '2025-03-17' THEN 1
                WHEN full_date >= '2025-10-03' THEN 1
                ELSE 0
            END) >= 4 AS is_ceasefire
        FROM main_mart.aid_events
        GROUP BY year, week_of_year, cargo_category
        ORDER BY year, week_of_year, cargo_category
""").df()

,year,week_of_year,cargo_category,start_of_week,sum_of_trucks,is_ceasefire
0,2023,42,Food Items,2023-10-21,16.0,False
1,2023,42,Medical Supplies,2023-10-21,14.0,False
2,2023,42,Mixed Items,2023-10-22,5.0,False
3,2023,43,Food Items,2023-10-23,57.0,False
4,2023,43,Medical Supplies,2023-10-23,30.0,False
...,...,...,...,...,...,...
251,2025,2,Mixed Items,2025-01-09,5.0,False
252,2025,2,Non-Food Items,2025-01-08,24.0,False
253,2025,3,Food Items,2025-01-13,55.0,False
254,2025,3,Mixed Items,2025-01-13,1.0,False
255,2025,3,Non-Food Items,2025-01-13,23.0,False

In [16]:
con = duckdb.connect("../dev.duckdb")
con.execute("""
SELECT * FROM main.fct_aid_received
""").df()

,aid_event_id,date_id,number_of_trucks,cargo_id,quantity,units,crossing_id,data_period,last_edited
0,75734,20250116,1,188c34a1bb6110fa8869ab5e1ae39350,22,Pallets,02ee1aad92e50f4e614224d0c8e9ff0e,Current Data (after Rafah Operation),2025-01-19 12:02:00
1,75735,20250116,1,188c34a1bb6110fa8869ab5e1ae39350,38,Pallets,02ee1aad92e50f4e614224d0c8e9ff0e,Current Data (after Rafah Operation),2025-01-19 12:02:00
2,75736,20250116,1,188c34a1bb6110fa8869ab5e1ae39350,16,Pallets,02ee1aad92e50f4e614224d0c8e9ff0e,Current Data (after Rafah Operation),2025-01-19 12:02:00
3,75737,20250116,1,188c34a1bb6110fa8869ab5e1ae39350,40,Pallets,02ee1aad92e50f4e614224d0c8e9ff0e,Current Data (after Rafah Operation),2025-01-19 12:02:00
4,75738,20250116,1,188c34a1bb6110fa8869ab5e1ae39350,44,Pallets,02ee1aad92e50f4e614224d0c8e9ff0e,Current Data (after Rafah Operation),2025-01-19 11:51:26
...,...,...,...,...,...,...,...,...,...
50054,22971,20231021,1,7a800f3932f93c27ea0be8c9b0d27cef,26,Pallets,7fd8e067e9058640e34904b3ac0d6fb8,Historical Data (before Rafah Operation),2024-01-20 22:09:26
50055,22972,20231021,1,7a800f3932f93c27ea0be8c9b0d27cef,26,Pallets,7fd8e067e9058640e34904b3ac0d6fb8,Historical Data (before Rafah Operation),2024-01-20 22:09:26
50056,22973,20231021,1,ccbefdc0f3904a50caeab64a55796cbd,20,Pallets,7fd8e067e9058640e34904b3ac0d6fb8,Historical Data (before Rafah Operation),2024-02-07 14:36:29
50057,22974,20231021,1,930ddca4a6ccd772100d27b100875683,24,Pallets,7fd8e067e9058640e34904b3ac0d6fb8,Historical Data (before Rafah Operation),2024-01-21 21:22:14
50058,22975,20231021,1,930ddca4a6ccd772100d27b100875683,30,Pallets,7fd8e067e9058640e34904b3ac0d6fb8,Historical Data (before Rafah Operation),2024-01-21 21:22:14

In [18]:
con.close()