In [1]:
import duckdb

con = duckdb.connect("../dev.duckdb")
con.execute("""
        SELECT
            year,
            week_of_year,
            cargo_category,
            MIN(full_date) AS start_of_week,
            SUM(number_of_trucks) AS sum_of_trucks,
            SUM(CASE
                WHEN full_date BETWEEN '2023-11-24' AND '2023-12-01' THEN 1
                WHEN full_date BETWEEN '2025-01-19' AND '2025-03-17' THEN 1
                WHEN full_date >= '2025-10-03' THEN 1
                ELSE 0
            END) >= 4 AS is_ceasefire
        FROM main_mart.aid_events
        GROUP BY year, week_of_year, cargo_category
        ORDER BY year, week_of_year, cargo_category
""").df()

,year,week_of_year,cargo_category,start_of_week,sum_of_trucks,is_ceasefire
0,2023,42,Food Items,2023-10-21,16.0,False
1,2023,42,Medical Supplies,2023-10-21,14.0,False
2,2023,42,Mixed Items,2023-10-22,5.0,False
3,2023,43,Food Items,2023-10-23,57.0,False
4,2023,43,Medical Supplies,2023-10-23,30.0,False
...,...,...,...,...,...,...
251,2025,2,Mixed Items,2025-01-09,5.0,False
252,2025,2,Non-Food Items,2025-01-08,24.0,False
253,2025,3,Food Items,2025-01-13,55.0,False
254,2025,3,Mixed Items,2025-01-13,1.0,False
255,2025,3,Non-Food Items,2025-01-13,23.0,False

In [4]:
con = duckdb.connect("../dev.duckdb")
con.execute("""
SELECT * FROM main.fct_commodity_prices
""").df()

                          commodity_id   date_id   price
0     c1e1778d6be9eebf4f6f026a01356c3c  20231101  38.667
1     c1e1778d6be9eebf4f6f026a01356c3c  20231201  50.000
2     c1e1778d6be9eebf4f6f026a01356c3c  20240101  45.000
3     c1e1778d6be9eebf4f6f026a01356c3c  20240201  60.000
4     c1e1778d6be9eebf4f6f026a01356c3c  20240301  55.000
...                                ...       ...     ...
1317  c72edd585db9722a513894d03b79c77b  20231001   2.240
1318  2922fefd28beb717e3d4e6b14ae532c3  20231001   7.000
1319  f29b927a1f21de58b1914d475972f4aa  20231001  13.330
1320  3d73d6893c3e8e6f66f67fb60b369095  20231001   2.000
1321  f2ce056c7be498614636813be6f70bc0  20231001   5.640

[1322 rows x 3 columns]

In [3]:
con.close()