In [1]:
import duckdb

con = duckdb.connect("../dev.duckdb")
con.execute("""
        SELECT
            year,
            week_of_year,
            cargo_category,
            MIN(full_date) AS start_of_week,
            SUM(number_of_trucks) AS sum_of_trucks,
            SUM(CASE
                WHEN full_date BETWEEN '2023-11-24' AND '2023-12-01' THEN 1
                WHEN full_date BETWEEN '2025-01-19' AND '2025-03-17' THEN 1
                WHEN full_date >= '2025-10-03' THEN 1
                ELSE 0
            END) >= 4 AS is_ceasefire
        FROM main_mart.aid_events
        GROUP BY year, week_of_year, cargo_category
        ORDER BY year, week_of_year, cargo_category
""").df()

,year,week_of_year,cargo_category,start_of_week,sum_of_trucks,is_ceasefire
0,2023,42,Food Items,2023-10-21,16.0,False
1,2023,42,Medical Supplies,2023-10-21,14.0,False
2,2023,42,Mixed Items,2023-10-22,5.0,False
3,2023,43,Food Items,2023-10-23,57.0,False
4,2023,43,Medical Supplies,2023-10-23,30.0,False
...,...,...,...,...,...,...
251,2025,2,Mixed Items,2025-01-09,5.0,False
252,2025,2,Non-Food Items,2025-01-08,24.0,False
253,2025,3,Food Items,2025-01-13,55.0,False
254,2025,3,Mixed Items,2025-01-13,1.0,False
255,2025,3,Non-Food Items,2025-01-13,23.0,False

In [2]:
con = duckdb.connect("../dev.duckdb")
con.execute("""
SELECT * FROM main.dim_cargo
""").df()

,cargo_id,items,cargo_category
0,367d974dd57797179c17b0c1f910eef9,Hygiene Kits + Food Parcels,Mixed Items
1,8d86bbdff82c6579c52aca77622e14ff,Canned Peas + Carrot,Food Items
2,a5d9685881e21ab03a28faa421640702,Medicine,Medical Supplies
3,d17414306a1576e7028bf53a06ba9825,Rice + Bulgur + Oil,Food Items
4,338e7fa436e2eb04f4be5f4e45cf255d,Canned Food,Food Items
...,...,...,...
2353,427867895b5fee8c646b2069c2810bee,Paper Supplies,Non-Food Items
2354,92e5071fd7714fd25c850ce54fb9756a,Tuna + Sauce,Food Items
2355,8790dcba02c6bbedc72a712949de7d62,Water + Body Bags,Mixed Items
2356,0fba603dfc493ad14496c762de0aa1c9,Medical Supplies + Milk,Mixed Items
2357,24b245c6d03bec229227a797db54dfcf,Tent + Kitchen Utensils,Non-Food Items

In [3]:
con.execute(
"""
SELECT
    table_name,
    column_name,
    data_type
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE table_name LIKE 'fct%'
""").df()

,table_name,column_name,data_type
0,fct_aid_received,aid_event_id,BIGINT
1,fct_aid_received,date_id,INTEGER
2,fct_aid_received,number_of_trucks,INTEGER
3,fct_aid_received,cargo_id,VARCHAR
4,fct_aid_received,donation_type,VARCHAR
5,fct_aid_received,quantity,INTEGER
6,fct_aid_received,units,VARCHAR
7,fct_aid_received,crossing_id,VARCHAR
8,fct_aid_received,data_period,VARCHAR
9,fct_aid_received,last_edited,TIMESTAMP
10,fct_aid_received,processed_date,TIMESTAMP WITH TIME ZONE
11,fct_aid_received__dbt_backup,aid_event_id,BIGINT
12,fct_aid_received__dbt_backup,date_id,INTEGER
13,fct_aid_received__dbt_backup,number_of_trucks,INTEGER
14,fct_aid_received__dbt_backup,cargo_id,VARCHAR
15,fct_aid_received__dbt_backup,donation_type,VARCHAR
16,fct_aid_received__dbt_backup,quantity,INTEGER
17,fct_aid_received__dbt_backup,units,VARCHAR
18,fct_aid_received__dbt_backup,crossing_id,VARCHAR
19,fct_aid_received__dbt_backup,data_period,VARCHAR
20,fct_aid_received__dbt_backup,last_edited,TIMESTAMP
21,fct_aid_received__dbt_backup,processed_date,TIMESTAMP WITH TIME ZONE
22,fct_commodity_prices,commodity_id,VARCHAR
23,fct_commodity_prices,date_id,INTEGER
24,fct_commodity_prices,price,DOUBLE
25,fct_commodity_prices,processed_date,TIMESTAMP WITH TIME ZONE
26,fct_commodity_prices__dbt_backup,commodity_id,VARCHAR
27,fct_commodity_prices__dbt_backup,date_id,INTEGER
28,fct_commodity_prices__dbt_backup,price,DOUBLE
29,fct_commodity_prices__dbt_backup,processed_date,TIMESTAMP WITH TIME ZONE

In [14]:
con = duckdb.connect("../dev.duckdb")

con.execute("""


""").df()

,commodity_id,date_id,price,processed_date,commodity_id_1
0,e38a0ca44d0e936d8d324b0088364d24,20240101,25.000,2026-09-18 17:19:40.117291+01:00,e38a0ca44d0e936d8d324b0088364d24
1,40c9a0de86a0e69d9a0ded96b85191b8,20240101,160.000,2026-09-18 17:19:40.117291+01:00,40c9a0de86a0e69d9a0ded96b85191b8
2,fc9b490fd72cdbef8ed361dc82c0eb31,20240101,15.500,2026-09-18 17:19:40.117291+01:00,fc9b490fd72cdbef8ed361dc82c0eb31
3,3ab8e5e194b5bda21287867e6e9dc0dc,20240101,80.000,2026-09-18 17:19:40.117291+01:00,3ab8e5e194b5bda21287867e6e9dc0dc
4,e38a0ca44d0e936d8d324b0088364d24,20240201,24.000,2026-09-18 17:19:40.117291+01:00,e38a0ca44d0e936d8d324b0088364d24
...,...,...,...,...,...
99,fc9b490fd72cdbef8ed361dc82c0eb31,20260101,2.429,2026-09-18 17:19:40.117291+01:00,fc9b490fd72cdbef8ed361dc82c0eb31
100,3ab8e5e194b5bda21287867e6e9dc0dc,20260201,34.118,2026-09-18 17:19:40.117291+01:00,3ab8e5e194b5bda21287867e6e9dc0dc
101,fc9b490fd72cdbef8ed361dc82c0eb31,20260201,1.455,2026-09-18 17:19:40.117291+01:00,fc9b490fd72cdbef8ed361dc82c0eb31
102,40c9a0de86a0e69d9a0ded96b85191b8,20260201,68.235,2026-09-18 17:19:40.117291+01:00,40c9a0de86a0e69d9a0ded96b85191b8
103,e38a0ca44d0e936d8d324b0088364d24,20260201,8.000,2026-09-18 17:19:40.117291+01:00,e38a0ca44d0e936d8d324b0088364d24

In [15]:
con.close()